version: "3.9"

services:

  postgres:
    image: postgres:16-alpine
    container_name: mediworld_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: mediworld_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: >
      postgres -c max_connections=200
               -c shared_buffers=256MB
               -c wal_level=logical

  redis:
    image: redis:7-alpine
    container_name: mediworld_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: >
      redis-server --appendonly yes
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
